### PR TITLE
Updated and consolidated font stacks

### PR DESCRIPTION
**Pull request by brentcas**

### CODE REVIEW

**Comment by brentcas** [comment]
Hey let me know if there are any issues! I'd be happy to discuss them.

**Comment by handrews** [comment]
Looks like some stray .DS_store files got added to the commit?  Take those out and I'd say this can be merged.  Sorry for the delay- you posted this when I was in the middle of my final class project and not paying attention to anything else, and by the time that was done I'd just forgotten.

**Comment by jochengcd** [comment]
Too much travelling the last days. I put this again on beta.comics.org (without the wrongly added files) so that people can have a final look.

**Comment by brentcas** [comment]
Ok, now it should be good to go.

**Comment by jochengcd** [comment]
From one user with: 
"Latest Firefox but really old OS(s), Windows Professional XP & 7, stuff like Segoe UI doesn't work very well without using "ClearType" to sharpen the font (Screenshots are without using it).
I'm more concerned with the bold Title/Features being so big now."

gcd_screen01a_beta
gcd_screen01a_live

Maybe there is another font option in the chain for this older setup ?

**Comment by jochengcd** [comment]
beta is the screenshot without the cover scan

**Comment by brentcas** [comment]
Hey sorry just seeing this now. I think the text looks very bad in both screenshots. Is ClearType turned off by default?

One solution to making the update not change the font rendering from the old version for this particular setup might be to put Segoe UI on the other side of Helvetica, and perhaps add Veranda ahead of Segoe so the stack would look something like this:

`-apple-system, BlinkMacSystemFont, "Roboto", "Oxygen", "Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",  "Verdana", "Segoe UI", sans-serif;`

The (pretty major) downside is that this would mean all Windows computers, wether they have standard rendering or not would be likely continue to see "Verdana" rather than their native Segoe.

Personally, I think the update is fine as is - what do you think?

**Comment by jochengcd** [comment]
No to Verdana:
Third, make sure you pay attention to the scale of the fonts in your stack. One common thing I see in font stacks is the inclusion of Verdana and Arial or Helvetica in the same stack. Verdana is a very wide font; Arial is relatively narrow. 
from
https://www.smashingmagazine.com/2009/09/complete-guide-to-css-font-stacks/

In the example brought up by a user the new font stack looks worse, so it seems like we need an alternative for Windows ? And this was the only real comment about the fonts in the beta, so I would prefer not to ignore it.

The other way people are suggesting font stacks is not based on system fonts, but on font families ?

Btw, the current order doesn't give me my system font (ubuntu) but roboto, which I actually like better for the website.

**Comment by jochengcd** [comment]
Hi Brent, how could we proceed here ? If I remember correctly, you are on a Mac ? So none of us three developers sees this on Windows, where the change seemingly does not work that well ? I'll try to have a look from a VM machine at work the next days.

Jochen

**Comment by brentcas** [comment]
Hey Jochen, it looks like GitHub has switched to start using this stack:

`font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, "Fira Sans", "Droid Sans", "Helvetica Neue", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol";`

I'll update the font stack and do another pull request and we can try that out. I have a Surface Book and I have Windows 10 running on my Mac so I can test Windows on those machines as well once everything is set up on beta. 

Apologies for the late reply, I've been working on a big project at my day job.

**Comment by handrews** [comment]
Hi Brent- please note that we moved the font changes to the font-changes branch so you will probably need to do something a bit awkward to sync your fork back up.  We had to do this because we are pushing some other changes through master.

I put some instructions for repairing master in a fork/clone on the gcd-tech list.  You may just want to force-sync the new state.

This is my fault for accepting a pull request to master when it needed to go on beta.  Lesson learned- always have a topic branch :-/

**Pull request merged**
