### PR TITLE
Allow delete of creator relations

### PR DESCRIPTION
**Pull request by adia**

### CODE REVIEW

**Comment by adia** [comment]
Deleting does work; I tested adding and deleting relations with and without sources and the history is correctly preserved in the oi tables while the relation is marked as deleted in the gcd tables and disappears from the creator pages.

The only thing missing is that the history is lost - I presume it should appear when viewing the creators' history, similar to the scan history for issues, but haven't looked into adding it yet.

Do you think we can merge this, or would you prefer a more complete patch to allow access to the history?

**Comment by jochengcd** [comment]
If we handle the creator links like this, we need the change history.

The other links (reprint and series) we handle differently, but then these don't have their own object pages.

Let me think on this once more, also looking at Henrys ideas for having a common underlying model. For normal data objects this is fine, but for the links I am not fully sure.

**Comment by adia** [comment]
Obsoleted by latest changes.

**Comment by jochengcd** [comment]
Actually it still is, I still haven't made up my mind about how to handle CreatorRelation on delete.

**Comment by jochengcd** [comment]
now added

**Pull request closed without merging**
