### PR TITLE
Updated font stacks for system defaults

### PR DESCRIPTION
**Pull request by brentcas**
Hey, I updated the font stacks in `default.css` to support using the user's system defaults. This should result in the site feeling more like other parts of their system. 

Here's some [light reading on how Medium uses this font stack](https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/).

### CODE REVIEW

**Comment by handrews** [comment]
Intriguing!  How well does this degrade on older browsers?  The GCD indexing community is not universally known for keeping up with the latest technology :-) although eventually pretty much everything switches over to an evergreen upgrade policy and we won't have to worry as much.

@jochengcd do you know what our oldest commonly used browser is?

**Comment by brentcas** [comment]
Hey sorry I commented on the Google Group instead of this thread!

Basically, this wouldn't require anything special from the browser. It would work the same way that the current font stack works. But instead of targeting the local "Verdana" font, it targets system fonts in an order where you'll get the right font for your OS. 

From a design standpoint it would be nice because it would make the site feel like other software on your computer. And personally I think Verdana is kind of a harse font to use.

**Comment by handrews** [comment]
I can't even remember why we picked Verdana.  I might have just grabbed those font lines from some example of how to do sans serif fonts circa 2008 or whatever.  We'll give Jochen a chance to see this before deciding to merge, but it sounds like a good idea to me.

**Comment by brentcas** [comment]
Sounds good, I'm open to any and all ideas.

**Comment by brentcas** [comment]
Hey just wanted to see if there are any issues I should resolve.

**Comment by shoebutton** [comment]
Jochen, can this be pulled or are there any issues?

**Comment by handrews** [comment]
Looks like Lionel is poking at Jochen- if he doesn't reply soon we'll just merge it and I'll check in with Lionel off list to make sure that no one will get upset if I just make the call on these going forwards.  It should be fine, there's just been some ambiguity about who should be approving what recently.  I'll get it sorted and this won't be a problem going forwards.
thanks,-henry

**Comment by jochengcd** [comment]
I put the change on beta.comics.org, please have a look how it changes the appearance on your system (you might need to do a "fresh" reload of the beta page to get the new css)

**Comment by gcd-github** [comment]
Gives a slightly different feel. Feels more open. I like it. Only tried it 
with Firefox on Win7 box at work. Will take a more in depth peek tonight 
when I get home. -ken

**Comment by brentcas** [comment]
I agree that we should fix the inconsistencies. I think the font stack should be consolidated to 1 line of code. I'll take a look at it tonight and assess it. I need to get the environment set up on my Mac so it might take me a day or two to finish the work.

**Comment by brentcas** [comment]
I'm running into some issues trying to set up my local VM. I started a Google Group thread if anyone can help me out there:

https://groups.google.com/forum/#!topic/gcd-tech/q-teN2YsICQ

**Comment by brentcas** [comment]
I created a new pull request so we can move the conversation there.

**Pull request closed without merging**
